services:
  - type: web
    name: nse-options-oca
    env: python
    pythonVersion: "3.12.4"
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      TELEGRAM_BOT_TOKEN:
        value: "8081075640:AAEDdrUSdg8BRX4CcKJ4W7jG1EOnSFTQPr4"
      TELEGRAM_CHAT_ID:
        value: "275529219"

